version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.6
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: ew79frt6497282081u4gf68evtydv3684767
        databases:
          default:
            connector: postgres
            host: ec2-54-246-117-62.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: d7l5hh2b1rervd
            ssl: true
            user: xytxnirrjgbtzc
            password: 9f4bbf20949db64bcd5a756e1a365a64d5bde4388ec7942e3cb4022b31174b34
            migrations: true
            rawAccess: true